### ISSUE TITLE
render_pkg["median_depth"] with artifacts vs render_pkg["expected_depth"] 

### ISSUE THREAD

**Issue by maorp** [BaowenZ/RaDe-GS#51]
Hi, first thanks for the nice work! I'm trying to use the depthmap directly and i see this difference between "median_depth" and "expected_depth" - which is much smoother and with less jumps but has "tails" of points to the background. see images below:
(these are pointclouds created from the depthmaps)
![image](https://github.com/user-attachments/assets/8f3a2c17-a07f-40cb-ac41-f4781816dc0b)
![image](https://github.com/user-attachments/assets/c375c603-07a2-485e-9a1b-e0463ac1536e)

**Comment by renhaofan** [comment]
@maorp  Could you let me know the reason?

**Comment by maorp** [comment]
Thanks! Is there a way to control it or improve it? Im happy to help coding it if needed

**Comment by BaowenZ** [comment]
I can't think of a complete solution. However, the "[stop the pop](https://github.com/r4dl/StopThePop)" proposed a better method to determine the order of kernels. Maybe it can improve the accuracy of median depth.

**Comment by outbreak-sen** [comment]
This is because the transmittance of Gaussian varies significantly at edge positions. Since the expected depth is computed as the average over the entire transmittance distribution, flying pixels (outliers) will occur. However, the transmittance remains at the correct position at 0.5. If we switch to median depth instead, these flying pixels will no longer appear.
